#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${BLUE}[ellavox]${NC} $1"; }
ok()   { echo -e "${GREEN}[ellavox]${NC} $1"; }
warn() { echo -e "${YELLOW}[ellavox]${NC} $1"; }
err()  { echo -e "${RED}[ellavox]${NC} $1"; }

# Helper: extract a JSON string value by key from supabase status --output json
json_val() {
  local json="$1" key="$2"
  echo "$json" | grep -o "\"${key}\": *\"[^\"]*\"" | head -1 | sed "s/\"${key}\": *\"\([^\"]*\)\"/\1/"
}

cleanup() {
  log "Shutting down..."
  kill $(jobs -p) 2>/dev/null || true
  wait 2>/dev/null || true
  ok "All processes stopped."
}
trap cleanup EXIT INT TERM

# ─── Preflight checks ───────────────────────────────────────────────────────

log "Running preflight checks..."

if ! command -v node &>/dev/null; then
  err "Node.js is required. Install it from https://nodejs.org"
  exit 1
fi

if ! command -v supabase &>/dev/null; then
  err "Supabase CLI is required. Install: brew install supabase/tap/supabase"
  exit 1
fi

if ! command -v redis-server &>/dev/null; then
  warn "Redis not found. Installing via Homebrew..."
  if command -v brew &>/dev/null; then
    brew install redis
  else
    err "Redis is required. Install it: brew install redis"
    exit 1
  fi
fi

if ! docker info &>/dev/null 2>&1; then
  err "Docker must be running for Supabase local dev."
  err "Start Docker Desktop, then re-run this script."
  exit 1
fi

if [ ! -d "node_modules" ]; then
  log "Installing npm dependencies..."
  npm install
fi

# ─── .env setup ──────────────────────────────────────────────────────────────

if [ ! -f ".env" ] && [ ! -f ".env.local" ]; then
  warn "No .env file found. Creating from .env.example..."
  cp .env.example .env
  warn "Edit .env with your credentials before using external services (Jira, Slack, etc.)"
fi

# ─── Start Supabase ─────────────────────────────────────────────────────────

log "Starting Supabase (Postgres, Auth, Storage, Realtime)..."

# Check if already running by trying to get status JSON
SUPABASE_JSON=$(supabase status --output json 2>/dev/null || echo '{}')

if [ "$SUPABASE_JSON" = "{}" ] || ! echo "$SUPABASE_JSON" | grep -q "API_URL"; then
  supabase start
  # Re-fetch status after start
  SUPABASE_JSON=$(supabase status --output json 2>/dev/null || echo '{}')
else
  ok "Supabase is already running."
fi

# Extract credentials from JSON output
SB_URL=$(json_val "$SUPABASE_JSON" "API_URL")
SB_ANON_KEY=$(json_val "$SUPABASE_JSON" "ANON_KEY")
SB_SERVICE_KEY=$(json_val "$SUPABASE_JSON" "SERVICE_ROLE_KEY")
SB_STUDIO_URL=$(json_val "$SUPABASE_JSON" "STUDIO_URL")
DB_URL=$(json_val "$SUPABASE_JSON" "DB_URL")

if [ -n "$SB_URL" ] && [ -n "$SB_SERVICE_KEY" ]; then
  cat > .env.local <<EOF
# Auto-generated by scripts/dev.sh — do not commit
SUPABASE_URL=${SB_URL}
SUPABASE_SERVICE_KEY=${SB_SERVICE_KEY}
NEXT_PUBLIC_SUPABASE_URL=${SB_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SB_ANON_KEY}
REDIS_HOST=localhost
REDIS_PORT=6379
NEXT_PUBLIC_APP_URL=http://localhost:3000
LOG_LEVEL=debug
EOF
  ok "Supabase credentials written to .env.local"
else
  warn "Could not extract Supabase credentials. Check 'supabase status'."
fi

# ─── Run migrations ─────────────────────────────────────────────────────────

log "Applying database migrations..."

if [ -n "${DB_URL:-}" ]; then
  for migration in supabase/migrations/*.sql; do
    if [ -f "$migration" ]; then
      log "  Applying $(basename "$migration")..."
      psql "$DB_URL" -f "$migration" -q 2>&1 | grep -v "^$" || warn "  Migration may have already been applied: $(basename "$migration")"
    fi
  done
  ok "Migrations applied."
else
  warn "Could not get DB URL. Run migrations manually."
fi

# ─── Start Redis ─────────────────────────────────────────────────────────────

if redis-cli ping &>/dev/null 2>&1; then
  ok "Redis is already running."
else
  log "Starting Redis..."
  redis-server --daemonize yes --loglevel warning
  sleep 1
  if redis-cli ping &>/dev/null 2>&1; then
    ok "Redis started."
  else
    err "Failed to start Redis."
    exit 1
  fi
fi

# ─── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Ellavox dev environment is ready!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BLUE}App:${NC}        http://localhost:3000"
[ -n "${SB_STUDIO_URL:-}" ] && echo -e "  ${BLUE}Supabase:${NC}   ${SB_STUDIO_URL}"
echo -e "  ${BLUE}Redis:${NC}      localhost:6379"
echo ""
echo -e "  Starting Next.js dev server + BullMQ worker..."
echo ""

# ─── Start app services ─────────────────────────────────────────────────────

# Worker in background
npx tsx src/worker.ts &
WORKER_PID=$!
ok "Worker started (PID: $WORKER_PID)"

# Next.js in foreground (Ctrl+C stops everything via trap)
npx next dev
