/**
 * Standalone worker process.
 * Run with: npm run worker
 *
 * This starts the BullMQ workers that process transcript extraction,
 * Jira creation, and maintenance jobs.
 */

// Load env files before anything else — Next.js does this automatically,
// but the standalone worker runs outside of Next.js.
import dotenv from "dotenv";
import { resolve } from "path";

const root = resolve(import.meta.dirname, "..");
// .env.local takes priority (auto-generated by dev.sh), then .env
dotenv.config({ path: resolve(root, ".env.local") });
dotenv.config({ path: resolve(root, ".env") });

import { startWorkers } from "./lib/jobs/processors";
import { setupMaintenanceJobs } from "./lib/jobs/queue";
import { logger } from "./lib/logger";

async function main() {
  logger.info("Starting Ellavox worker process...");

  // Start all workers
  const workers = startWorkers();

  // Set up recurring maintenance jobs
  await setupMaintenanceJobs();

  logger.info("Worker process running. Press Ctrl+C to stop.");

  // Graceful shutdown
  const shutdown = async () => {
    logger.info("Shutting down workers...");
    await workers.transcriptWorker.close();
    await workers.jiraWorker.close();
    await workers.maintenanceWorker.close();
    logger.info("Workers stopped.");
    process.exit(0);
  };

  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
}

main().catch((err) => {
  logger.fatal({ err }, "Worker process crashed");
  process.exit(1);
});
